### ISSUE TITLE
Awesome lists checklist

### ISSUE THREAD

**Issue by metov** [metov/awesome-browser#4]
Some interesting milestones, based on https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list:

- [ ] Wait at least until Dec 10, 2022
- [ ] Set up https://github.com/sindresorhus/awesome-lint #6 
- [ ] Default branch should be `main`
- [ ] Succinct description at the top of the readme
- [ ] Put considerable effort into the list :p
- [ ] Github topics: `awesome-list`, `awesome`, ...
- [ ] Project logo/illustration (optional)
- [ ] Has TOC

I'm not sure yet if it's useful to actually raise a PR against that repo, but these are useful guidelines for improving the list.
